mod change;
mod clock;
mod jump;
mod spike;
mod spike_death;
mod star;
mod star_switch;
mod static_block;
mod straight;
mod switch;
mod teleport;

pub use change::*;
pub use clock::*;
pub use jump::*;
pub use spike::*;
pub use spike_death::*;
pub use star::*;
pub use star_switch::*;
pub use static_block::*;
pub use straight::*;
pub use switch::*;
pub use teleport::*;
